"""empty message

Revision ID: 2494650267fc
Revises: 41aa03671575
Create Date: 2015-10-31 13:08:06.585000

"""

# revision identifiers, used by Alembic.
revision = '2494650267fc'
down_revision = '41aa03671575'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('brand_id', table_name='shop')
    op.create_foreign_key(None, 'shop', 'brand', ['brand_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shop', type_='foreignkey')
    op.create_index('brand_id', 'shop', ['brand_id'], unique=True)
    ### end Alembic commands ###
