"""empty message

Revision ID: 3db1cf477796
Revises: 2494650267fc
Create Date: 2015-10-31 13:17:15.037000

"""

# revision identifiers, used by Alembic.
revision = '3db1cf477796'
down_revision = '2494650267fc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brand', sa.Column('create_at', sa.DateTime(), nullable=True))
    op.add_column('brand', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'brand', 'user', ['user_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'brand', type_='foreignkey')
    op.drop_column('brand', 'user_id')
    op.drop_column('brand', 'create_at')
    ### end Alembic commands ###
