"""empty message

Revision ID: 41aa03671575
Revises: 44ed8bab7ea2
Create Date: 2015-10-31 12:31:23.430000

"""

# revision identifiers, used by Alembic.
revision = '41aa03671575'
down_revision = '44ed8bab7ea2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('industry_1', sa.String(length=50), nullable=True),
    sa.Column('industry_2', sa.String(length=50), nullable=True),
    sa.Column('intro', sa.Text(), nullable=True),
    sa.Column('image', sa.String(length=200), nullable=True),
    sa.Column('thumb', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('shop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('store', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=400), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('province', sa.String(length=20), nullable=True),
    sa.Column('city', sa.String(length=20), nullable=True),
    sa.Column('dist', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('lng', sa.String(length=20), nullable=True),
    sa.Column('lat', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shop')
    op.drop_table('brand')
    ### end Alembic commands ###
